receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

processors:
  batch:

exporters:
  elasticsearch:
    endpoint: "http://elasticsearch:9200"
  debug: {}

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [elasticsearch]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [elasticsearch]

    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [elasticsearch]